from funciones import *
from ventana3 import Win_3

class Win_2 (QWidget):
    def __init__(self):
        super().__init__()
        self.set_appear()
        self.initUI()
        self.connect()
        self.show()
        app.exec_() 

    def set_appear(self):
        self.setWindowTitle(txt_title)
        self.resize(win_width, win_height)
        self.move(win_x, win_y)

    def initUI(self):
        self.imagenviej = QLabel(self)
        pixmapviej = QPixmap("imgviej.png")
        self.imagenviej.setPixmap(pixmapviej)
        self.imagenviej.setScaledContents(True)
        self.imagenviej.setFixedSize(150, 100)
        self.imagenfla = QLabel(self)
        pixmapfla = QPixmap("imgest.png")
        self.imagenfla.setPixmap(pixmapfla)
        self.imagenfla.setScaledContents(True)
        self.imagenfla.setFixedSize(150, 100)
        self.imagenest = QLabel(self)
        pixmapest = QPixmap("imest.png")
        self.imagenest.setPixmap(pixmapest)
        self.imagenest.setScaledContents(True)
        self.imagenest.setFixedSize(150, 100)
        self.texto_princ = QLabel (txt_n)
        self.texto_in1 = QLabel (txt_len1)
        self.intr_texto1 = QLineEdit (txt_le1)
        int_validator1 = QIntValidator(0, 999, self)
        self.intr_texto1.setValidator(int_validator1)
        self.texto_in2 = QLabel (txt_len2)
        self.intr_texto2 = QLineEdit (txt_le2)
        int_validator2 = QDoubleValidator(0.0, 999.0, 2, self)
        self.intr_texto2.setValidator(int_validator2)
        self.texto_in3 = QLabel (txt_len3)
        self.intr_texto3 = QLineEdit (txt_le3)
        self.intr_texto3.setValidator(int_validator2)
        #_N_W significa nueva ventana
        self.boton_N_V = QPushButton (txt_buttom_next)
        self.H_layout = QHBoxLayout()
        self.V_layout = QVBoxLayout()
        self.V2_layout = QVBoxLayout()
        self.V2_layout.addWidget(self.imagenest)
        self.V2_layout.addWidget(self.imagenviej)
        self.V2_layout.addWidget(self.imagenfla)
        self.V_layout.addWidget(self.texto_princ)
        self.V_layout.addWidget(self.texto_in1)
        self.V_layout.addWidget(self.intr_texto1)
        self.V_layout.addWidget(self.texto_in2)
        self.V_layout.addWidget(self.intr_texto2)
        self.V_layout.addWidget(self.texto_in3)
        self.V_layout.addWidget(self.intr_texto3)
        self.V_layout.addWidget(self.boton_N_V)
        self.H_layout.addLayout(self.V_layout)
        self.H_layout.addLayout(self.V2_layout)
        self.setLayout(self.H_layout)

    def connect(self):
        self.boton_N_V.clicked.connect(self.next_click)
    def next_click (self):
        self.hide()
        self.camb_pan2 = Win_3(self.intr_texto1, self.intr_texto2, self.intr_texto3)
